export { Home } from './Home';
export { SignUp } from './SignUp';
export { SignIn } from './SignIn';
export { Nav } from './Nav';
export { configFirebase } from './firebase';
export { NotFound } from './NotFound';
export { DashBoard } from './DashBoard';
export { Customers } from './Customers';
export { AddMeasurment } from './AddMeasurment';
export { history } from './history';
export { addTailor, store, checkCustomer, addMeasurmentR, addOrder, checkOrder , checkMeasurment} from './store';
export { AddDetail } from './AddDetail';
export { AddOrder } from './AddOrder';
